on:
  push:
    paths: 
      - "**.md"
  pull_request:
    paths: 
      - "**.md"

name: 'markdown checks'

jobs:
  dead-links:
    name: Dead Link Checker
    runs-on: ubuntu-latest
    steps:
    - name: Run DeadFinder
      uses: hahwul/deadfinder@1.2.4
      id: broken-link
      with:
        command: file
        target: "**.md"

  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint changelog file
      uses: avto-dev/markdown-lint@v1
      with:
        args: '**.md'
