name: 'markdown checks'
on:
  push:
    paths: 
      - "**.md"
  pull_request:
    paths: 
      - "**.md"

jobs:
  dead-links:
    name: Dead Link Checker
    runs-on: ubuntu-latest
    steps:
    - name: Run DeadFinder
      uses: hahwul/deadfinder@1.2.4
      id: broken-link
      with:
        command: file
        target: "**.md"
