on:
  push:
  pull_request:

name: 'QA'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        version: v0.7.2
      env:
        SHELLCHECK_OPTS: -s sh -e 1087 -e 2059 -o all -e 2250

  markdown-link-check:
    name: Dead Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint-changelog:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint Readme
      uses: avto-dev/markdown-lint@v1
      with:
        args: 'README.md'
