on:
  push:
  pull_request:

name: 'QA'

jobs:
  sh-checker:
    name: Shellcheck & Shfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the sh-checker
      uses: luizm/action-sh-checker@master
      env:
        SHELLCHECK_OPTS: -s sh -o all -e 2250
        SHFMT_OPTS: -i 4 -ci -d

  dead-links:
    name: Dead Link Checker
    runs-on: ubuntu-latest
    steps:
    - name: Run DeadFinder
      uses: hahwul/deadfinder@1.2.4
      id: broken-link
      with:
        command: file
        target: "./README.md"
    - name: Output Handling
      run: echo '${{ steps.broken-link.outputs.output }}'
      
  check-exec:
    name: Check for executable bit
    runs-on: ubuntu-latest
    steps:
    - name: test exec bit
      run: test -x "./ani-cli"
  
  master-pr-check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if version changed
      uses: port19x/action-pr-version-check@v0.1.1
      with:
        file: ./ani-cli
