on:
  push:
  pull_request:

name: 'QA'

jobs:
  sh-checker:
    name: Sh-Checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the sh-checker
      uses: luizm/action-sh-checker@master
      env:
        SHELLCHECK_OPTS: -s sh -o all -e 2250
        SHFMT_OPTS: -i 4 -ci -d
